version: '3'
services:
    web:
        container_name: Web
        build: 
            context: .
            dockerfile: ./conf/Dockerfile
        ports:
            - '8181:80'
        volumes:
            - './web:/var/www/'
            - './conf/sri.asir4all.ss.conf:/etc/apache2/sites-available/000-default.conf'
